## Permutation-based sorting

In [13]:
n = 4

4

In [28]:
function sgn(x)
    if x > 0 
       return 1 
    elseif x == 0
        return 0.5
    else
        return 0
    end
end

sgn (generic function with 1 method)

In [29]:
function rotsum(v, n)
    new_v = v + circshift(v, -n)
    max_shift = Int(floor(log2(n)))
    
    for i in 1:max_shift-1
        shift_amt = n * 2^i
        new_v = new_v + circshift(new_v, -shift_amt)
    end
    new_v
end

rotsum (generic function with 1 method)

In [30]:
v = [2, 7, 1, 6]

4-element Vector{Int64}:
 2
 7
 1
 6

In [31]:
v_repeated = repeat(v, n)

16-element Vector{Int64}:
 2
 7
 1
 6
 2
 7
 1
 6
 2
 7
 1
 6
 2
 7
 1
 6

In [32]:
v_expanded = repeat(v, inner=(n,))

16-element Vector{Int64}:
 2
 2
 2
 2
 7
 7
 7
 7
 1
 1
 1
 1
 6
 6
 6
 6

In [33]:
delta = v_expanded - v_repeated 

16-element Vector{Int64}:
  0
 -5
  1
 -4
  5
  0
  6
  1
 -1
 -6
  0
 -5
  4
 -1
  5
  0

In [34]:
sgn_delta = sgn.(delta)

16-element Vector{Real}:
 0.5
 0
 1
 0
 1
 0.5
 1
 1
 0
 0
 0.5
 0
 1
 0
 1
 0.5

In [35]:
s = rotsum(sgn_delta, n)

16-element Vector{Float64}:
 2.5
 0.5
 3.5
 1.5
 2.5
 0.5
 3.5
 1.5
 2.5
 0.5
 3.5
 1.5
 2.5
 0.5
 3.5
 1.5

In [36]:
s = s .+ 0.5

16-element Vector{Float64}:
 3.0
 1.0
 4.0
 2.0
 3.0
 1.0
 4.0
 2.0
 3.0
 1.0
 4.0
 2.0
 3.0
 1.0
 4.0
 2.0

In [37]:
units = repeat([1,2,3,4], inner=(n,))

16-element Vector{Int64}:
 1
 1
 1
 1
 2
 2
 2
 2
 3
 3
 3
 3
 4
 4
 4
 4

In [38]:
units - s

16-element Vector{Float64}:
 -2.0
  0.0
 -3.0
 -1.0
 -1.0
  1.0
 -2.0
  0.0
  0.0
  2.0
 -1.0
  1.0
  1.0
  3.0
  0.0
  2.0

In [39]:
columns = sinc.(units - s)

16-element Vector{Float64}:
 0.0
 1.0
 0.0
 0.0
 0.0
 0.0
 0.0
 1.0
 1.0
 0.0
 0.0
 0.0
 0.0
 0.0
 1.0
 0.0

In [40]:
P = reshape(columns, n, n)

4×4 Matrix{Float64}:
 0.0  0.0  1.0  0.0
 1.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0
 0.0  1.0  0.0  0.0

In [41]:
P * v

4-element Vector{Float64}:
 1.0
 2.0
 6.0
 7.0